{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "automend.serviceAccountName" . }}
  labels:
    {{- include "automend.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    # GKE Workload Identity binding lives here:
    #   iam.gke.io/gcp-service-account: automend-app@<project>.iam.gserviceaccount.com
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- with .Values.global.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
automountServiceAccountToken: true
{{- end -}}
