# ---------------------------------------------------------------------------
# The instance. STANDARD_HA with auth + server-auth TLS. Private IP only —
# the VPC peering set up in the root module (shared with Cloud SQL) gives us
# a private IP automatically.
# ---------------------------------------------------------------------------

resource "google_redis_instance" "primary" {
  project        = var.project_id
  name           = var.instance_name
  region         = var.region
  tier           = var.tier
  memory_size_gb = var.memory_size_gb
  redis_version  = var.redis_version

  # Private IP on the VPC. `reserved_ip_range` intentionally omitted so
  # Memorystore picks a free block from the PSA peering range owned by
  # the root module.
  authorized_network      = var.authorized_network
  connect_mode            = "PRIVATE_SERVICE_ACCESS"

  # AUTH string — auto-generated by Google. Read via .auth_string attribute
  # below and written into Secret Manager.
  auth_enabled = true

  # Server-auth TLS (client does not need a cert; trusts Memorystore's CA).
  # Clients must connect over 6379/TLS and validate against server_ca_certs.
  transit_encryption_mode = "SERVER_AUTHENTICATION"

  labels = var.labels

  # Weekly maintenance window — aligned with Cloud SQL's Sunday 03:00 UTC.
  maintenance_policy {
    weekly_maintenance_window {
      day = "SUNDAY"
      start_time {
        hours   = 3
        minutes = 0
        seconds = 0
        nanos   = 0
      }
    }
  }
}

# ---------------------------------------------------------------------------
# Secret Manager — auth string. Memorystore generates it; we just persist it
# into a secret the app can read.
# ---------------------------------------------------------------------------

resource "google_secret_manager_secret" "auth" {
  project   = var.project_id
  secret_id = "${var.instance_name}-auth"

  replication {
    auto {}
  }

  labels = var.labels
}

resource "google_secret_manager_secret_version" "auth" {
  secret      = google_secret_manager_secret.auth.id
  secret_data = google_redis_instance.primary.auth_string
}

# ---------------------------------------------------------------------------
# IAM — scoped permissions for the app service account.
#
# `roles/redis.editor` lets the SA describe + update (not delete) instances
# in the project. AutoMend doesn't actually need this today (redis-py
# connects directly with host + port + auth), but 12.6's External Secrets
# operator + future diagnostic tooling (check instance state on startup)
# lean on it.
# ---------------------------------------------------------------------------

resource "google_project_iam_member" "app_redis_viewer" {
  project = var.project_id
  role    = "roles/redis.viewer"
  member  = "serviceAccount:${var.app_service_account_email}"
}

resource "google_secret_manager_secret_iam_member" "app_auth_accessor" {
  project   = var.project_id
  secret_id = google_secret_manager_secret.auth.secret_id
  role      = "roles/secretmanager.secretAccessor"
  member    = "serviceAccount:${var.app_service_account_email}"
}
