# Version + provider pins.
#
# Terraform itself is pinned via `.terraform-version` (tfenv-compatible) and
# mirrored here so `terraform init` errors out clearly if an unsupported
# version is in use.
#
# Provider versions use `~> x.y` (pessimistic constraint) so minor-version
# upgrades are automatic but a major version bump requires an explicit edit.
# The `.terraform.lock.hcl` file generated by `terraform init` pins the exact
# resolved versions + hashes and IS checked into git.

terraform {
  required_version = ">= 1.9.0, < 2.0.0"

  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 6.0"
    }
    google-beta = {
      source  = "hashicorp/google-beta"
      version = "~> 6.0"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.30"
    }
    helm = {
      source  = "hashicorp/helm"
      version = "~> 2.13"
    }
  }
}
